<a href="https://colab.research.google.com/github/listarova-aleksandra/I_to_I/blob/main/lab_4_Data_preprocessing_and_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа 'Предобработка и анализ данных'

**Получим общую информацию о датасете**

In [68]:
import pandas as pd

In [69]:
df = pd.read_csv('games.csv')

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16715 non-null  object
 2   Year_of_Release  16446 non-null  float64
 3   Genre            16713 non-null  object
 4   NA_sales         16715 non-null  float64
 5   EU_sales         16715 non-null  float64
 6   JP_sales         16715 non-null  float64
 7   Other_sales      16715 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   User_Score       10014 non-null  object
 10  Rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

In [71]:
df.head(10)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,23.20,2.26,4.22,0.58,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,14.44,6.94,4.70,2.24,87.0,8.4,E
9,Duck Hunt,NES,1984.0,Shooter,26.93,0.63,0.28,0.47,NaN,NaN,NaN

In [72]:
df.tail(10)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
16705,15 Days,PC,2009.0,Adventure,0.00,0.01,0.00,0.0,63.0,5.8,NaN
16706,Men in Black II: Alien Escape,GC,2003.0,Shooter,0.01,0.00,0.00,0.0,NaN,tbd,T
16707,Aiyoku no Eustia,PSV,2014.0,Misc,0.00,0.00,0.01,0.0,NaN,NaN,NaN
16708,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,0.01,0.00,0.00,0.0,NaN,NaN,NaN
16709,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,0.00,0.00,0.00,0.0,NaN,NaN,NaN
16710,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.00,0.01,0.0,NaN,NaN,NaN
16711,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.0,NaN,NaN,NaN
16712,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.00,0.01,0.0,NaN,NaN,NaN
16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.0,NaN,NaN,NaN
16714,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.00,0.01,0.0,NaN,NaN,NaN

In [73]:
df.shape

(16715, 11)

In [74]:
df.describe()

,Year_of_Release,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score
count,16446.000000,16715.000000,16715.000000,16715.000000,16715.000000,8137.000000
mean,2006.484616,0.263377,0.145060,0.077617,0.047342,68.967679
std,5.877050,0.813604,0.503339,0.308853,0.186731,13.938165
min,1980.000000,0.000000,0.000000,0.000000,0.000000,13.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,60.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,71.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,79.000000
max,2016.000000,41.360000,28.960000,10.220000,10.570000,98.000000

In [75]:
df.columns

Index(['Name', 'Platform', 'Year_of_Release', 'Genre', 'NA_sales', 'EU_sales',
       'JP_sales', 'Other_sales', 'Critic_Score', 'User_Score', 'Rating'],
      dtype='object')

**Подготовка данных**

**Как можно заметить названия столбцов идут с большой буквы. Для удобства приведу названия столбцов к нижнему регистру.**

In [76]:
df.columns = df.columns.str.lower()
df.columns

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating'],
      dtype='object')

**Теперь необходимо разобраться с типами данных. Для этого вопользуюсь функцией info(). Эта функция позволяет посмотреть, какие типы данных есть в датасете**

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16713 non-null  object
 1   platform         16715 non-null  object
 2   year_of_release  16446 non-null  float64
 3   genre            16713 non-null  object
 4   na_sales         16715 non-null  float64
 5   eu_sales         16715 non-null  float64
 6   jp_sales         16715 non-null  float64
 7   other_sales      16715 non-null  float64
 8   critic_score     8137 non-null   float64
 9   user_score       10014 non-null  object
 10  rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

**В столбце user_score есть есть значения 'tbd'. 'tbd' - это аббревиатура для выражений 'to be determined' или 'to be decided'. То есть это обзначает, что оценка еще не была присвоена. Поэтому, я думаю, что будет лучше изменить эти значения на None. Так как это показывает, что в этом значении есть пропуск данных, то есть нет реальных значений. Также стоит преобразовать этот стоолбец в тип float, так как сейчас там данные нечислового типа.**

In [78]:
df['user_score'] = df['user_score'].replace('tbd', None).astype(float)

**Теперь перейду анализу пропусков. Их много особенно в столбцах critic_score, user_score, rating, year_of_release.**

**Почему в этих столбцах могут быть пропуски: ошибки в сборе данных, неполные сведения от источника. В столбцах critic_score, user_score могут быть пропуски, так как это может быть непопулярная игра, и ее никто не оценивал. Подобная ситуайия также может быть в столбце rating - эта игра могла не проходить оценку ESRB.**

**Попробую вначале разобраться со столбцом year_of_release. Возможно, в какой-то определенный период из-за ошибки при сборе данных появились пропуски. Надо проверить эту гипотезу:**

In [79]:
missing_year_rows = df[df['year_of_release'].isna()]
missing_year_rows

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
183,Madden NFL 2004,PS2,NaN,Sports,4.26,0.26,0.01,0.71,94.0,8.5,E
377,FIFA Soccer 2004,PS2,NaN,Sports,0.59,2.36,0.04,0.51,84.0,6.4,E
456,LEGO Batman: The Videogame,Wii,NaN,Action,1.80,0.97,0.00,0.29,74.0,7.9,E10+
475,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,1.57,1.02,0.00,0.41,NaN,NaN,NaN
609,Space Invaders,2600,NaN,Shooter,2.36,0.14,0.00,0.03,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16373,PDC World Championship Darts 2008,PSP,NaN,Sports,0.01,0.00,0.00,0.00,43.0,NaN,E10+
16405,Freaky Flyers,GC,NaN,Racing,0.01,0.00,0.00,0.00,69.0,6.5,T
16448,Inversion,PC,NaN,Shooter,0.01,0.00,0.00,0.00,59.0,6.7,M
16458,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16522,Virtua Quest,GC,NaN,Role-Playing,0.01,0.00,0.00,0.00,55.0,5.5,T

**Мое предположение провалилось. Эти игры были выпущенны в разное время, поэтому не получится заполнить пропуски таким способом.**

**В играх, которые посвящены спорту, в названии часто упоминается год релиза. Опираясь на это, можно попробовать заполнить спропуски.**

In [80]:
sport_games_missing_year = df[(df['year_of_release'].isna()) & (df['genre'] == 'Sports')]
sport_games_missing_year

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
183,Madden NFL 2004,PS2,NaN,Sports,4.26,0.26,0.01,0.71,94.0,8.5,E
377,FIFA Soccer 2004,PS2,NaN,Sports,0.59,2.36,0.04,0.51,84.0,6.4,E
1301,Triple Play 99,PS,NaN,Sports,0.81,0.55,0.00,0.10,NaN,NaN,NaN
2479,Madden NFL 07,PSP,NaN,Sports,0.77,0.03,0.00,0.04,78.0,6.6,E
2492,MLB SlugFest 20-03,PS2,NaN,Sports,0.41,0.32,0.00,0.11,77.0,8.2,E
2536,Shaun White Snowboarding,X360,NaN,Sports,0.48,0.25,0.00,0.08,60.0,7.6,T
2572,PES 2009: Pro Evolution Soccer,PSP,NaN,Sports,0.04,0.33,0.26,0.17,NaN,NaN,NaN
2849,Madden NFL 11,Wii,NaN,Sports,0.68,0.00,0.00,0.04,75.0,5.4,E
3413,Madden NFL 06,X360,NaN,Sports,0.54,0.00,0.01,0.03,74.0,4.9,E
3486,Madden NFL 2002,XB,NaN,Sports,0.53,0.02,0.00,0.03,90.0,8.1,E
3739,NBA Street Vol. 2,GC,NaN,Sports,0.41,0.11,0.00,0.01,88.0,8.1,E
3883,Fishing Derby,2600,NaN,Sports,0.48,0.03,0.00,0.01,NaN,NaN,NaN
4205,Tiger Woods PGA Tour 07,Wii,NaN,Sports,0.43,0.00,0.00,0.04,71.0,6.9,E
4635,NHL Slapshot,Wii,NaN,Sports,0.39,0.00,0.00,0.02,76.0,8.1,E
4775,NFL GameDay 2003,PS2,NaN,Sports,0.20,0.15,0.00,0.05,60.0,NaN,E
5156,NBA Live 2003,XB,NaN,Sports,0.31,0.04,0.00,0.01,82.0,8.8,E
5655,All-Star Baseball 2005,PS2,NaN,Sports,0.16,0.12,0.00,0.04,72.0,8.6,E
5889,NBA Live 2003,GC,NaN,Sports,0.23,0.06,0.00,0.01,82.0,8.2,E
6624,College Hoops 2K6,PS2,NaN,Sports,0.12,0.10,0.00,0.03,77.0,7.3,E
6636,Jonah Lomu Rugby Challenge,PS3,NaN,Sports,0.00,0.19,0.00,0.06,64.0,NaN,E
6999,Tony Hawk's Downhill Jam,Wii,NaN,Sports,0.21,0.00,0.00,0.02,69.0,6.2,E10+
7108,Big Beach Sports 2,Wii,NaN,Sports,0.09,0.11,0.00,0.02,NaN,NaN,E
7387,Move Fitness,PS3,NaN,Sports,0.00,0.16,0.00,0.05,NaN,NaN,NaN
7605,Famista 64,N64,NaN,Sports,0.00,0.00,0.17,0.03,NaN,NaN,NaN
8067,Backbreaker,X360,NaN,Sports,0.17,0.00,0.00,0.01,54.0,7.6,E
8197,NBA Starting Five,PS2,NaN,Sports,0.09,0.07,0.00,0.02,53.0,7.3,E
8260,Backbreaker,PS3,NaN,Sports,0.16,0.00,0.00,0.01,58.0,7.0,E
8740,Home Run,2600,NaN,Sports,0.14,0.01,0.00,0.00,NaN,NaN,NaN
8918,All-Star Baseball 2005,XB,NaN,Sports,0.11,0.03,0.00,0.01,75.0,8.8,E
9380,Transworld Surf,XB,NaN,Sports,0.10,0.03,0.00,0.00,76.0,NaN,T
9817,Street Hoops,GC,NaN,Sports,0.09,0.02,0.00,0.00,56.0,7.3,T
9876,Major League Baseball 2K6,PSP,NaN,Sports,0.11,0.00,0.00,0.01,69.0,NaN,E
10486,Atsumare! Power Pro Kun no DS Koushien,DS,NaN,Sports,0.00,0.00,0.10,0.00,NaN,NaN,NaN
11550,Get Fit with Mel B,X360,NaN,Sports,0.00,0.06,0.00,0.01,57.0,NaN,E
12959,Mountain Bike Adrenaline,PS2,NaN,Sports,0.03,0.02,0.00,0.01,NaN,NaN,E
13792,NHL Hitz Pro,GC,NaN,Sports,0.03,0.01,0.00,0.00,81.0,7.8,E
14141,Major League Baseball 2K8,PSP,NaN,Sports,0.03,0.00,0.00,0.00,63.0,NaN,E
15338,Mario Tennis,3DS,NaN,Sports,0.00,0.00,0.02,0.00,NaN,NaN,NaN
15675,Cabela's Alaskan Adventure,PS2,NaN,Sports,0.01,0.01,0.00,0.00,NaN,NaN,NaN
15953,PDC World Championship Darts 2008,DS,NaN,Sports,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16079,Football Manager 2007,X360,NaN,Sports,0.00,0.01,0.00,0.00,NaN,NaN,NaN
16373,PDC World Championship Darts 2008,PSP,NaN,Sports,0.01,0.00,0.00,0.00,43.0,NaN,E10+

**Смотря на получившийся датафрейм, можно понять, что иногда эта теория верна. Но иногда числа могут быть частью нейминга. Я думаю, что обработка пропусков таким образом принесет больше проблем, нежели внесет ясность. Поэтому откажусь от этого способа.**

**Теперь подключу немного статистики к этой проблеме. Всего столбцов с пропущеннным годом релиза 269. Это составляет 1.6% от всех данных. Исходя из этого, можно заключить, что пропуски в этом стобце можно оставить, так как существенной разницы при определении закономерности успешности игры это не сыграет.**

In [81]:
df['year_of_release'] = df['year_of_release'].fillna(0).astype(int)

****

**Перейду к работе над пропусками critic_score, user_score. Мне кажется, что над пропуски в этих столбцах можно обрабтать одинаковым способом. Оценки игроков и критиков не могут принимать отрицательные значения, поэтому для удобства пропуски можно заполнить значениями -1.**

In [82]:
df['critic_score'] = df['critic_score'].fillna(-1).astype(int)

In [83]:
df['user_score'] = df['user_score'].fillna(-1).astype(int)

****

**Отлично. Осталось разобраться с пропусками в столбце rating. В целом, пропуски можно оставить со значенями None, но мне хочется заполнить эти значения unknown.**

In [84]:
df['rating'] = df['rating'].fillna('unknown')

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16713 non-null  object
 1   platform         16715 non-null  object
 2   year_of_release  16715 non-null  int64
 3   genre            16713 non-null  object
 4   na_sales         16715 non-null  float64
 5   eu_sales         16715 non-null  float64
 6   jp_sales         16715 non-null  float64
 7   other_sales      16715 non-null  float64
 8   critic_score     16715 non-null  int64
 9   user_score       16715 non-null  int64
 10  rating           16715 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 1.4+ MB

**Ура. Остались два пропуска в столбце name. Можно их вывести.**

In [86]:
missing_name = df[df['name'].isna()]
missing_name

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
659,NaN,GEN,1993,NaN,1.78,0.53,0.00,0.08,-1,-1,unknown
14244,NaN,GEN,1993,NaN,0.00,0.00,0.03,0.00,-1,-1,unknown

**Об этих играх почти нет информации. От объема всех данных эти игры составляют составляют меньше одного процента, поэтому эти две сторки можно удалить.**

In [87]:
df = df.dropna(subset=['name'])

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16713 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16713 non-null  object
 1   platform         16713 non-null  object
 2   year_of_release  16713 non-null  int64
 3   genre            16713 non-null  object
 4   na_sales         16713 non-null  float64
 5   eu_sales         16713 non-null  float64
 6   jp_sales         16713 non-null  float64
 7   other_sales      16713 non-null  float64
 8   critic_score     16713 non-null  int64
 9   user_score       16713 non-null  int64
 10  rating           16713 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 1.5+ MB

**С пропусками разобралась. Теперь можно переходить к следующему этапу работы над датафреймом.**